name: üõ°Ô∏è Check PR Title

on:
  pull_request:
    types: [opened, edited]

jobs:
  lint-pr-title:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v5.0.0
        with:
          # Only fetch the config file from the repository
          sparse-checkout-cone-mode: false
          sparse-checkout: .commitlintrc.yml

      - name: Install dependencies
        run: npm install --global @commitlint/config-conventional commitlint

      - name: Check PR title with commitlint
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
          HELP_URL: https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md#conventional-pr-titles
        run: echo "$PR_TITLE" | npx commitlint --help-url $HELP_URL
